name: Generate feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate feeds
        run: python script.py
      - name: Commit results
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.rss
          git commit -m "Update feeds"
          git push